name: CI-SFTP
 
# Controla cuándo se ejecutará la acción.
on:
  # Activa el workflow en eventos push o pull request pero sólo para la rama que elijas.
  push:
    branches: [ main ]
 # pull_request:
   # branches: [ main ]
 
  # workflow_dispatch: Le permite ejecutar este workflow manualmente desde la pestaña Acciones.
  workflow_dispatch:
 
# Un workflow se compone de uno o varios jobs que pueden ejecutarse de forma secuencial o en paralelo.
jobs:
  # Este workflow contiene un solo job llamado "SFTP".
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          # username: Nombre de usuario con el cual nos conectaremos al servidor.
          username: pruebafreeman
          # server: Nombre del servidor o IP.
          server: files.000webhost.com
          port: 21 
          ssh_private_key: oNcMBM@%d&nSeaB&o7us

          # local_path: Ruta dentro del repositorio la cual quieres copiar en el servidor,por defecto es ./*
          local_path: ./*
          
          # remote_path: Ruta remota donde se copiaran los archivos del repositorio.
          remote_path: /public_html/
          
          # SFTP args
          args: '-o ConnectTimeout=5'
